version: '3.7'

x-default: &default
  restart: always
  env_file: .env

services:
  wp:
    <<: *default
    build: .
    volumes:
      - ./uploads.ini:/usr/local/etc/php/conf.d/uploads.ini:ro
      - ./data/wp:/var/www/html
      - ./liquet:/var/www/html/wp-content/themes/liquet:ro
    ports:
      - 80:80

  db:
    <<: *default
    image: mariadb:10.3
    volumes:
      - ./data/db:/var/lib/mysql